### ISSUE TITLE
GOPATH is not set.

### ISSUE THREAD

**Issue by paulviks** [openhoangnc/vscode-io-run#2]
Hello,
I install this great extension, but when try to run in output window i see this  fail:
`[main.go] compiling... error!
main.go:6:2: cannot find package "github.com/labstack/echo" in any of:
	/usr/local/go/src/github.com/labstack/echo (from $GOROOT)
	($GOPATH not set. For more details see: 'go help gopath')`
Global variable GOPATH is visible in terminal(zsh)
Best regards,
Paul

**Comment by openhoangnc** [comment]
@paulviks Thanks for submitting your issue.
The fix for this issue has been released with the latest update to the IORun extension (v1.0.7)

**Comment by paulviks** [comment]
Thanks :)
